<template>
  <div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
    <div>goods</div>
  </div>
</template>
